myServer:  
	g++ myServer.cpp Acceptor.cpp Connection.cpp Epoll.cpp HttpData.cpp InetAddress.cpp Pages.cpp Responser.cpp Socket.cpp TaskQueue.cpp ThreadPool.cpp Timer.cpp utils.cpp -o /home/embark/myServer/myServer -I/home/embark/myServer/include -pthread

.PHONY:clean
clean:
	rm -f myServer 